services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3721:3721"  # React development server
      - "3722:3722"  # Express backend server
    volumes:
      - .:/app
      - /app/node_modules
      - files-data:/app/files  # Use a named volume for the files folder
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

volumes:
  files-data:  # Define the named volume