services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3721:3721"  # React development server
      - "3722:3722"  # Express backend server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development