services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3666:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true